'use client';

import { useState, useEffect } from 'react';
import { X, TrendingUp, Clock, ArrowRight, Download } from 'lucide-react';
import { SDG_LIST } from '@/lib/sdg';
import { calculateGaps, GapAnalysisResult, TargetClassification } from '@/lib/gap-analysis';

interface Props {
  sdgId:          number;
  currentScore:   number;
  classification: string;
  submittedData:  Record<string, number | null>;
  onClose:        () => void;
}

const EFFORT_STYLE = {
  low:    { color: '#00A651', bg: 'rgba(0,166,81,0.1)',   label: 'Quick win'  },
  medium: { color: '#E8A020', bg: 'rgba(232,160,32,0.1)', label: '~1 quarter' },
  high:   { color: '#D0021B', bg: 'rgba(208,2,27,0.08)',  label: 'Long-term'  },
};

const IMPACT_STYLE = {
  primary:   { label: 'High impact', color: 'var(--sanlam-teal)' },
  secondary: { label: 'Also helps',  color: 'var(--text-muted)'  },
};

export default function GapAnalysisPanel({
  sdgId, currentScore, classification, submittedData, onClose,
}: Props) {
  const sdg = SDG_LIST.find(s => s.id === sdgId);

  const [target, setTarget] = useState<TargetClassification>(
    classification === 'Low' ? 'Medium' : 'High'
  );
  const [result, setResult] = useState<GapAnalysisResult | null>(null);

  useEffect(() => {
    const r = calculateGaps(sdgId, currentScore, classification, target, submittedData);
    setResult(r);
  }, [sdgId, currentScore, classification, target, submittedData]);

  const handleExport = () => {
    if (!result) return;
    const lines = [
      `InvestScore — Gap Analysis`,
      `SDG ${sdgId}: ${sdg?.name}`,
      `Current: ${classification} (${currentScore.toFixed(1)})`,
      `Target: ${target} Impact`,
      ``,
      `REQUIRED CHANGES:`,
      ...result.gaps.map(g => `• ${g.label}: ${g.changeLabel} (${g.effortLabel})`),
      ``,
      result.summary,
      ``,
      `Generated by InvestScore · Sanlam Investments · Twin Transition Challenge 2026`,
    ];
    const blob = new Blob([lines.join('\n')], { type: 'text/plain' });
    const url  = URL.createObjectURL(blob);
    const a    = document.createElement('a');
    a.href     = url;
    a.download = `SDG${sdgId}_Gap_Analysis.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  if (!result) return null;

  const scoreColor = (s: number) => s >= 2.4 ? '#00A651' : s >= 1.6 ? '#E8A020' : '#D0021B';

  const availableTargets = (['Medium', 'High'] as TargetClassification[]).filter(t => {
    if (classification === 'Low')    return true;
    if (classification === 'Medium') return t === 'High';
    return false;
  });

  return (
    <>
      <div className="fixed inset-0 bg-black/20 z-40" onClick={onClose} />
      <div
        className="fixed right-0 top-0 h-full z-50 flex flex-col"
        style={{
          width:      '380px',
          maxWidth:   '100vw',
          background: 'var(--surface)',
          borderLeft: '1px solid var(--border)',
          animation:  'slideInRight 250ms cubic-bezier(0.16, 1, 0.3, 1) forwards',
          overflowY:  'auto',
        }}
      >
        <div className="h-1.5 w-full flex-shrink-0" style={{ background: sdg?.color }} />

        <div className="flex-1 p-5">

          {/* Header */}
          <div className="flex items-start justify-between mb-5">
            <div className="flex items-center gap-3">
              <span className="text-2xl">{sdg?.icon}</span>
              <div>
                <p className="font-bold text-base" style={{ color: 'var(--text-primary)' }}>
                  Gap Analysis
                </p>
                <p className="text-xs" style={{ color: 'var(--text-muted)' }}>
                  SDG {sdgId} — {sdg?.shortName}
                </p>
              </div>
            </div>
            <button
              onClick={onClose}
              className="p-1.5 rounded-lg transition"
              style={{ color: 'var(--text-muted)' }}
              onMouseEnter={e => (e.currentTarget.style.background = 'var(--bg)')}
              onMouseLeave={e => (e.currentTarget.style.background = 'transparent')}
            >
              <X size={16} />
            </button>
          </div>

          {/* Current → Target selector */}
          <div className="rounded-2xl p-4 mb-5" style={{ background: 'var(--bg)' }}>
            <div className="flex items-center gap-3 mb-4">

              <div className="text-center flex-1">
                <p className="text-[11px] uppercase tracking-wider mb-1" style={{ color: 'var(--text-muted)' }}>
                  Current
                </p>
                <p className="font-bold text-xl" style={{ color: scoreColor(currentScore) }}>
                  {currentScore.toFixed(1)}
                </p>
                <span
                  className="text-[10px] font-semibold px-2 py-0.5 rounded-full"
                  style={{ background: `${scoreColor(currentScore)}15`, color: scoreColor(currentScore) }}
                >
                  {classification}
                </span>
              </div>

              <ArrowRight size={18} style={{ color: 'var(--text-muted)', flexShrink: 0 }} />

              <div className="text-center flex-1">
                <p className="text-[11px] uppercase tracking-wider mb-1" style={{ color: 'var(--text-muted)' }}>
                  Target
                </p>
                <div className="flex gap-1.5 justify-center">
                  {availableTargets.map(t => {
                    const tc = t === 'High' ? '#00A651' : '#E8A020';
                    return (
                      <button
                        key={t}
                        onClick={() => setTarget(t)}
                        className="px-3 py-1.5 rounded-lg text-xs font-semibold transition-all"
                        style={{
                          background: target === t ? `${tc}15`         : 'var(--surface)',
                          color:      target === t ? tc                 : 'var(--text-muted)',
                          border:     `1.5px solid ${target === t ? tc + '40' : 'var(--border)'}`,
                        }}
                      >
                        {t}
                      </button>
                    );
                  })}
                </div>
              </div>
            </div>

            <div
              className="flex items-center justify-center gap-2 py-2 rounded-xl"
              style={{ background: result.feasibleThisQuarter ? 'rgba(0,166,81,0.08)' : 'rgba(232,160,32,0.08)' }}
            >
              {result.feasibleThisQuarter
                ? <TrendingUp size={13} style={{ color: '#00A651' }} />
                : <Clock      size={13} style={{ color: '#E8A020' }} />
              }
              <p className="text-xs font-semibold" style={{ color: result.feasibleThisQuarter ? '#00A651' : '#E8A020' }}>
                {result.feasibleThisQuarter ? 'Achievable this quarter' : 'Multi-quarter effort'}
              </p>
            </div>
          </div>

          {/* Summary */}
          <p className="text-sm leading-relaxed mb-5" style={{ color: 'var(--text-muted)', lineHeight: '1.7' }}>
            {result.summary}
          </p>

          {/* Gap list */}
          {result.gaps.length === 0 ? (
            <div
              className="text-center py-6 rounded-2xl"
              style={{ background: 'rgba(0,166,81,0.06)', border: '1px solid rgba(0,166,81,0.2)' }}
            >
              <p className="text-2xl mb-2">✓</p>
              <p className="text-sm font-semibold" style={{ color: '#00A651' }}>
                Already at {target} Impact
              </p>
              <p className="text-xs mt-1" style={{ color: 'var(--text-muted)' }}>
                All KPIs for this SDG meet the {target} threshold
              </p>
            </div>
          ) : (
            <div>
              <div className="flex items-center justify-between mb-3">
                <p className="text-xs font-semibold uppercase tracking-wider" style={{ color: 'var(--text-muted)' }}>
                  Required changes
                </p>
                <span className="text-xs" style={{ color: 'var(--text-muted)' }}>
                  {result.totalEffortLabel}
                </span>
              </div>

              <div className="space-y-2">
                {result.gaps.map((gap, idx) => {
                  const es = EFFORT_STYLE[gap.effort];
                  const is = IMPACT_STYLE[gap.impact];

                  return (
                    <div
                      key={gap.kpiId}
                      className="rounded-xl p-3.5 animate-card-in"
                      style={{
                        background:     'var(--bg)',
                        border:         '1px solid var(--border)',
                        animationDelay: `${idx * 40}ms`,
                      }}
                    >
                      <div className="flex items-start justify-between gap-2 mb-2">
                        <div className="flex-1 min-w-0">
                          <p className="text-xs font-semibold" style={{ color: 'var(--text-primary)' }}>
                            {gap.label}
                          </p>
                          <div className="flex items-center gap-2 mt-0.5">
                            <span
                              className="text-[9px] font-semibold px-1.5 py-0.5 rounded"
                              style={{
                                background: is.color === 'var(--text-muted)' ? 'var(--border)' : `${is.color}15`,
                                color: is.color,
                              }}
                            >
                              {is.label}
                            </span>
                            <span
                              className="text-[9px] font-semibold px-1.5 py-0.5 rounded"
                              style={{ background: es.bg, color: es.color }}
                            >
                              {es.label}
                            </span>
                          </div>
                        </div>
                      </div>

                      <div
                        className="flex items-center justify-between py-2 px-3 rounded-lg"
                        style={{ background: 'var(--surface)' }}
                      >
                        <div className="flex items-center gap-3">
                          <div className="text-center">
                            <p className="text-[10px]" style={{ color: 'var(--text-muted)' }}>Current</p>
                            <p className="text-xs font-bold" style={{ color: 'var(--text-primary)' }}>
                              {gap.currentValue !== null
                                ? gap.unit === 'ZAR'
                                  ? `R${gap.currentValue.toLocaleString('en-ZA')}`
                                  : `${gap.currentValue} ${gap.unit}`
                                : 'Not reported'}
                            </p>
                          </div>
                          <ArrowRight size={12} style={{ color: 'var(--text-muted)' }} />
                          <div className="text-center">
                            <p className="text-[10px]" style={{ color: 'var(--text-muted)' }}>Need</p>
                            <p className="text-xs font-bold" style={{ color: '#00A651' }}>
                              {gap.unit === 'ZAR'
                                ? `R${gap.targetValue.toLocaleString('en-ZA')}`
                                : `${gap.targetValue} ${gap.unit}`}
                            </p>
                          </div>
                        </div>
                        <p className="text-[11px] font-semibold" style={{ color: es.color }}>
                          {gap.changeLabel}
                        </p>
                      </div>
                    </div>
                  );
                })}
              </div>
            </div>
          )}

          <button
            onClick={handleExport}
            className="w-full flex items-center justify-center gap-2 h-11 rounded-xl text-sm font-semibold mt-5 transition"
            style={{ background: 'var(--bg)', border: '1px solid var(--border)', color: 'var(--text-muted)' }}
            onMouseEnter={e => (e.currentTarget.style.background = 'var(--surface)')}
            onMouseLeave={e => (e.currentTarget.style.background = 'var(--bg)')}
          >
            <Download size={14} />
            Download action checklist
          </button>

          <p className="text-[10px] text-center mt-3" style={{ color: 'var(--text-muted)' }}>
            Calculations are based on Sanlam's proprietary KPI thresholds.
            Exact score movements depend on all KPIs together, not individual metrics.
          </p>
        </div>
      </div>
    </>
  );
}
