export type ValueType = 'numeric' | 'percentage' | 'level';
export type KPICategory =
  | 'employment'
  | 'environmental'
  | 'transformation'
  | 'community'
  | 'financial_services'
  | 'water'
  | 'manufacturing'
  | 'retail'
  | 'logistics'
  | 'ict'
  | 'housing';

export interface KPIDefinition {
  id:          string;
  name:        string;
  description: string;
  unit:        string;
  valueType:   ValueType;
  category:    KPICategory;
  sdgs:        number[];   // Which SDGs this KPI maps to
  helpText:    string;     // Plain-language explanation for SME portal
  calculation: string;     // How to calculate it
}

export const KPI_LIST: KPIDefinition[] = [
  // EMPLOYMENT
  {
    id: 'total_employees',
    name: 'Total number of employees',
    description: 'Total number of employees working in the company.',
    unit: 'Number',
    valueType: 'numeric',
    category: 'employment',
    sdgs: [8],
    helpText: 'Count every person on your payroll - full-time, part-time, and permanent staff. Do not include contractors here.',
    calculation: 'Count all employees on your payroll as of your financial year end date.',
  },
  {
    id: 'youth_employees',
    name: 'Number of employees (Youth)',
    description: 'Total number of young employees (under 35) working in the company.',
    unit: 'Number',
    valueType: 'numeric',
    category: 'employment',
    sdgs: [8],
    helpText: 'Youth is defined as employees aged 35 and under.',
    calculation: 'Count all employees aged 35 and under as of your financial year end date.',
  },
  {
    id: 'management_employees',
    name: 'Total number of employees (Management)',
    description: 'Number of employees in leadership or supervisory roles.',
    unit: 'Number',
    valueType: 'numeric',
    category: 'employment',
    sdgs: [8],
    helpText: 'Include anyone who manages people or holds a senior title (Manager, Director, Head of, C-suite).',
    calculation: 'Count employees in management or supervisory roles.',
  },
  {
    id: 'staff_employees',
    name: 'Total number of employees (Staff)',
    description: 'Number of regular employees who are not in management.',
    unit: 'Number',
    valueType: 'numeric',
    category: 'employment',
    sdgs: [8],
    helpText: 'All employees who are not in management roles. This is your total employees minus management.',
    calculation: 'Total employees minus management employees.',
  },
  {
    id: 'contractor_employees',
    name: 'Total number of employees (Contractor)',
    description: 'Number of workers hired on a contract basis.',
    unit: 'Number',
    valueType: 'numeric',
    category: 'employment',
    sdgs: [8],
    helpText: 'Count anyone working for you on a fixed-term or project contract who is not a permanent employee.',
    calculation: 'Count all active contractors during the reporting period.',
  },
  {
    id: 'black_employees',
    name: 'Total number of employees (Black)',
    description: 'Number of Black employees.',
    unit: 'Number',
    valueType: 'numeric',
    category: 'employment',
    sdgs: [10],
    helpText: 'As per B-BBEE legislation: African, Coloured, and Indian South African citizens.',
    calculation: 'Count all employees who identify as Black (African, Coloured, or Indian) as per B-BBEE definitions.',
  },
  {
    id: 'white_employees',
    name: 'Total number of employees (White)',
    description: 'Number of White employees.',
    unit: 'Number',
    valueType: 'numeric',
    category: 'employment',
    sdgs: [10],
    helpText: 'Count all employees who identify as White.',
    calculation: 'Count all employees who identify as White.',
  },
  {
    id: 'coloured_employees',
    name: 'Total number of employees (Coloured)',
    description: 'Number of Coloured employees.',
    unit: 'Number',
    valueType: 'numeric',
    category: 'employment',
    sdgs: [10],
    helpText: 'As per B-BBEE classification.',
    calculation: 'Count all employees who identify as Coloured as per B-BBEE definitions.',
  },
  {
    id: 'indian_employees',
    name: 'Total number of employees (Indian)',
    description: 'Number of Indian employees.',
    unit: 'Number',
    valueType: 'numeric',
    category: 'employment',
    sdgs: [10],
    helpText: 'As per B-BBEE classification.',
    calculation: 'Count all employees who identify as Indian as per B-BBEE definitions.',
  },
  {
    id: 'female_employees',
    name: 'Total number of employees (Female)',
    description: 'Total number of female employees.',
    unit: 'Number',
    valueType: 'numeric',
    category: 'employment',
    sdgs: [5],
    helpText: 'Count all employees who identify as female across all levels.',
    calculation: 'Count all female employees.',
  },
  {
    id: 'male_employees',
    name: 'Total number of employees (Male)',
    description: 'Total number of male employees.',
    unit: 'Number',
    valueType: 'numeric',
    category: 'employment',
    sdgs: [5],
    helpText: 'Count all employees who identify as male across all levels.',
    calculation: 'Count all male employees.',
  },

  // ENVIRONMENTAL
  {
    id: 'recycled_waste_pct',
    name: 'Recycled waste (%)',
    description: 'Percentage of total waste that is recycled.',
    unit: '%',
    valueType: 'percentage',
    category: 'environmental',
    sdgs: [12, 13, 15],
    helpText: 'What percentage of your total waste gets recycled rather than going to landfill?',
    calculation: '(Total waste recycled / Total waste generated) × 100',
  },
  {
    id: 'scope1_co2e',
    name: 'Scope 1 CO2e',
    description: 'Direct greenhouse gas emissions from operations.',
    unit: 'tCO2e',
    valueType: 'numeric',
    category: 'environmental',
    sdgs: [7, 13],
    helpText: 'These are emissions from sources you own or control - fuel burned in company vehicles, generators, on-site boilers.',
    calculation: 'Sum all direct GHG emissions in tonnes of CO2 equivalent (tCO2e).',
  },
  {
    id: 'scope2_co2e',
    name: 'Scope 2 CO2e',
    description: 'Indirect emissions from purchased electricity.',
    unit: 'tCO2e',
    valueType: 'numeric',
    category: 'environmental',
    sdgs: [7, 13],
    helpText: 'Emissions from electricity you buy from the grid (Eskom). Your electricity supplier can provide emission factors.',
    calculation: 'Electricity consumed (kWh) × Eskom emission factor (currently ~0.93 kgCO2e/kWh) ÷ 1000',
  },
  {
    id: 'renewable_energy_produced',
    name: 'Total renewable energy produced',
    description: 'Total renewable energy generated by the company.',
    unit: 'kWh',
    valueType: 'numeric',
    category: 'environmental',
    sdgs: [7, 13],
    helpText: 'If you have solar panels or other renewable energy sources, record how much energy they generated.',
    calculation: 'Total kWh generated by solar, wind, or other renewable sources on your premises.',
  },
  {
    id: 'renewable_energy_utilised',
    name: 'Renewable energy utilised (kWh)',
    description: 'Amount of renewable energy used by the company.',
    unit: 'kWh',
    valueType: 'numeric',
    category: 'environmental',
    sdgs: [7, 13],
    helpText: 'Of the renewable energy available to you (produced or purchased), how much did you actually use?',
    calculation: 'kWh of renewable energy consumed during the reporting period.',
  },
  {
    id: 'total_water_consumption',
    name: 'Total water consumption',
    description: 'Total volume of water used in operations.',
    unit: 'kL',
    valueType: 'numeric',
    category: 'environmental',
    sdgs: [3, 6, 14],
    helpText: 'Read your water meter at the start and end of the year. The difference is your consumption.',
    calculation: 'Total kilolitres of water consumed from all sources during the reporting period.',
  },
  {
    id: 'total_energy_consumption_renewable',
    name: 'Total energy consumption (renewable)',
    description: 'Total energy consumed from renewable sources.',
    unit: 'kWh',
    valueType: 'numeric',
    category: 'environmental',
    sdgs: [7],
    helpText: 'Total energy from renewable sources - solar, wind, hydro - consumed during the year.',
    calculation: 'Sum of all renewable energy consumed in kWh.',
  },
  {
    id: 'electricity_consumption',
    name: 'Total electricity consumption (kWh)',
    description: 'Total electricity consumed from the Eskom grid.',
    unit: 'kWh',
    valueType: 'numeric',
    category: 'environmental',
    sdgs: [7],
    helpText: 'Your electricity bill shows your monthly consumption in kWh. Add up the full year.',
    calculation: 'Sum of monthly electricity bills in kWh for the reporting period.',
  },

  // TRANSFORMATION (B-BBEE)
  {
    id: 'bbbee_rating',
    name: "Company's BBBEE rating",
    description: 'B-BBEE scorecard level (1–8).',
    unit: 'Level 1-8',
    valueType: 'level',
    category: 'transformation',
    sdgs: [10, 16],
    helpText: 'Your B-BBEE certificate shows your level. Level 1 is best, Level 8 is lowest. Non-compliant = 0.',
    calculation: 'Enter your current B-BBEE certification level as issued by an accredited verification agency.',
  },
  {
    id: 'black_ownership_pct',
    name: '% Black Ownership',
    description: 'Percentage of company owned by Black individuals.',
    unit: '%',
    valueType: 'percentage',
    category: 'transformation',
    sdgs: [10],
    helpText: 'What percentage of your company shares or equity is held by Black South African citizens?',
    calculation: '(Black-owned equity / Total equity) × 100',
  },
  {
    id: 'black_female_ownership_pct',
    name: '% Black Female Ownership',
    description: 'Percentage of company owned by Black women.',
    unit: '%',
    valueType: 'percentage',
    category: 'transformation',
    sdgs: [5, 10],
    helpText: 'Of your total equity, what percentage is held by Black women?',
    calculation: '(Black female-owned equity / Total equity) × 100',
  },
  {
    id: 'black_board_pct',
    name: '% Black Board Representation',
    description: 'Percentage of board members who are Black.',
    unit: '%',
    valueType: 'percentage',
    category: 'transformation',
    sdgs: [10, 16],
    helpText: 'Of your total board seats, what percentage are held by Black individuals?',
    calculation: '(Black board members / Total board members) × 100',
  },
  {
    id: 'black_board_number',
    name: 'No. Black Board Representation',
    description: 'Number of Black individuals on the board.',
    unit: 'Number',
    valueType: 'numeric',
    category: 'transformation',
    sdgs: [16],
    helpText: 'Count the number of Black individuals currently serving on your board of directors.',
    calculation: 'Count Black board members.',
  },
  {
    id: 'procurement_black_owned_pct',
    name: '% Procurement Spend to Black-owned Suppliers',
    description: 'Percentage of procurement spend to Black-owned suppliers.',
    unit: '%',
    valueType: 'percentage',
    category: 'transformation',
    sdgs: [10, 17],
    helpText: 'Of your total supplier spend, what percentage went to suppliers that are majority Black-owned (51%+)?',
    calculation: '(Spend with Black-owned suppliers / Total procurement spend) × 100',
  },
  {
    id: 'procurement_women_owned_pct',
    name: '% Procurement Spend to Women-owned Suppliers',
    description: 'Percentage of procurement spend to women-owned suppliers.',
    unit: '%',
    valueType: 'percentage',
    category: 'transformation',
    sdgs: [5, 17],
    helpText: 'Of your total supplier spend, what percentage went to suppliers that are majority women-owned?',
    calculation: '(Spend with women-owned suppliers / Total procurement spend) × 100',
  },
  {
    id: 'total_annual_revenue',
    name: 'Total Annual Revenue',
    description: 'Total revenue from business activities for the year.',
    unit: 'ZAR',
    valueType: 'numeric',
    category: 'transformation',
    sdgs: [8],
    helpText: 'Your total income before any deductions. This is on your income statement as "Revenue" or "Turnover".',
    calculation: 'Total revenue as reported on your annual financial statements in ZAR.',
  },

  // COMMUNITY
  {
    id: 'csi_spend',
    name: 'Amount spent on CSI',
    description: 'Total Corporate Social Investment expenditure.',
    unit: 'ZAR',
    valueType: 'numeric',
    category: 'community',
    sdgs: [1],
    helpText: 'Total rand amount spent on community development, charity, or social programmes.',
    calculation: 'Sum all CSI expenditure during the reporting period in ZAR.',
  },
  {
    id: 'local_suppliers',
    name: 'Number of Local Suppliers',
    description: 'Number of suppliers based in the same country.',
    unit: 'Number',
    valueType: 'numeric',
    category: 'community',
    sdgs: [17],
    helpText: 'Count the number of South African-based suppliers you use.',
    calculation: 'Count unique South African suppliers used during the reporting period.',
  },
  {
    id: 'smes_in_supply_chain',
    name: 'Number of SMEs in Supply Chain',
    description: 'Number of SME suppliers in the supply chain.',
    unit: 'Number',
    valueType: 'numeric',
    category: 'community',
    sdgs: [8, 17],
    helpText: 'Of your suppliers, how many qualify as SMEs (turnover under R50 million)?',
    calculation: 'Count SME suppliers (annual turnover < R50 million) used during the reporting period.',
  },

  // FINANCIAL SERVICES SPECIFIC
  {
    id: 'smes_funded',
    name: 'Number of SMEs funded',
    description: 'Total number of SMEs that received financial support.',
    unit: 'Number',
    valueType: 'numeric',
    category: 'financial_services',
    sdgs: [1],
    helpText: 'How many SMEs did your business provide funding or investment to during the year?',
    calculation: 'Count unique SMEs that received funding during the reporting period.',
  },
  {
    id: 'black_smes_funded_pct',
    name: '% Black-owned SMEs funded',
    description: 'Percentage of funded SMEs that are majority Black-owned.',
    unit: '%',
    valueType: 'percentage',
    category: 'financial_services',
    sdgs: [10],
    helpText: 'Of the SMEs you funded, what percentage are majority Black-owned (51%+ Black ownership)?',
    calculation: '(Black-owned SMEs funded / Total SMEs funded) × 100',
  },
  {
    id: 'women_led_smes_funded_pct',
    name: '% Women-led SMEs funded',
    description: 'Percentage of funded SMEs led by women.',
    unit: '%',
    valueType: 'percentage',
    category: 'financial_services',
    sdgs: [5],
    helpText: 'Of the SMEs you funded, what percentage have a woman in a senior leadership role?',
    calculation: '(Women-led SMEs funded / Total SMEs funded) × 100',
  },
  {
    id: 'capital_deployed_smes',
    name: 'Total capital deployed to SMEs (ZAR)',
    description: 'Total funding disbursed to SMEs.',
    unit: 'ZAR',
    valueType: 'numeric',
    category: 'financial_services',
    sdgs: [1],
    helpText: 'Total rand value of funding, loans, or investment deployed to SMEs during the year.',
    calculation: 'Sum all capital disbursed to SMEs in ZAR during the reporting period.',
  },
  {
    id: 'jobs_supported_smes',
    name: 'Jobs supported through funded SMEs',
    description: 'Number of jobs maintained or created within funded SMEs.',
    unit: 'Number',
    valueType: 'numeric',
    category: 'financial_services',
    sdgs: [1],
    helpText: 'How many jobs exist within the SMEs you funded? Ask your portfolio companies to report this.',
    calculation: 'Sum of total employees across all funded SMEs as reported by those SMEs.',
  },

  // MANUFACTURING SPECIFIC
  {
    id: 'units_produced',
    name: 'Units produced',
    description: 'Total finished products manufactured during the period.',
    unit: 'Number',
    valueType: 'numeric',
    category: 'manufacturing',
    sdgs: [8, 9],
    helpText: 'Total number of finished goods produced during the reporting period.',
    calculation: 'Count total units of finished products manufactured.',
  },
  {
    id: 'manufacturing_revenue_pct',
    name: '% Revenue from manufacturing/industrial activities',
    description: 'Percentage of revenue from manufacturing operations.',
    unit: '%',
    valueType: 'percentage',
    category: 'manufacturing',
    sdgs: [8],
    helpText: 'What percentage of your total revenue comes from manufacturing or industrial activities?',
    calculation: '(Manufacturing revenue / Total revenue) × 100',
  },
  {
    id: 'local_raw_material_pct',
    name: '% local raw material sourcing',
    description: 'Percentage of raw materials sourced locally.',
    unit: '%',
    valueType: 'percentage',
    category: 'manufacturing',
    sdgs: [2, 12, 15],
    helpText: 'Of your raw materials, what percentage comes from South African suppliers?',
    calculation: '(Local raw material spend / Total raw material spend) × 100',
  },
  {
    id: 'apprentices_supported',
    name: 'Number of Apprentices / Trainees supported',
    description: 'Total individuals in apprenticeship or training programmes.',
    unit: 'Number',
    valueType: 'numeric',
    category: 'manufacturing',
    sdgs: [4],
    helpText: 'Count all apprentices, interns, or learnership participants your company supported during the year.',
    calculation: 'Count all individuals in formal training or apprenticeship programmes.',
  },

  // RETAIL SPECIFIC
  {
    id: 'products_local_producers_pct',
    name: '% of products sourced from small/local producers',
    description: 'Percentage of products from small or local producers.',
    unit: '%',
    valueType: 'percentage',
    category: 'retail',
    sdgs: [2, 12],
    helpText: 'Of the products you sell, what percentage come from small or local South African producers?',
    calculation: '(Products from local/small producers / Total products) × 100',
  },
  {
    id: 'low_income_customers',
    name: 'Customer reach (low-income or underserved customers)',
    description: 'Number of low-income or underserved customers served.',
    unit: 'Number',
    valueType: 'numeric',
    category: 'retail',
    sdgs: [1],
    helpText: 'How many customers from low-income or underserved communities does your business serve?',
    calculation: 'Count customers from LSM 1–5 or formally defined underserved segments.',
  },
  {
    id: 'sustainable_products_pct',
    name: '% of sustainable/ethical products sold',
    description: 'Percentage of products meeting sustainability standards.',
    unit: '%',
    valueType: 'percentage',
    category: 'retail',
    sdgs: [12],
    helpText: 'Of the products you sell, what percentage carry an environmental or ethical certification?',
    calculation: '(Certified sustainable products sold / Total products sold) × 100',
  },

  // ICT SPECIFIC
  {
    id: 'spectrum_units',
    name: 'Number of spectrum units made available',
    description: 'Radio frequency spectrum units made available nationally.',
    unit: 'Number',
    valueType: 'numeric',
    category: 'ict',
    sdgs: [9],
    helpText: 'Number of spectrum units made available for communication services.',
    calculation: 'Count spectrum units allocated or made available during the reporting period.',
  },
  {
    id: 'new_customers_connected',
    name: 'Number of new customers served/connected',
    description: 'New customers gaining access to your service.',
    unit: 'Number',
    valueType: 'numeric',
    category: 'ict',
    sdgs: [9],
    helpText: 'How many new customers were connected to your service during the year?',
    calculation: 'Count new customer connections during the reporting period.',
  },
  {
    id: 'geographic_coverage_km2',
    name: 'Total geographic area covered (km²)',
    description: 'Land area where the project has impact.',
    unit: 'km²',
    valueType: 'numeric',
    category: 'ict',
    sdgs: [9],
    helpText: 'Total square kilometres covered by your service or network.',
    calculation: 'Total km² of geographic service coverage.',
  },
  {
    id: 'average_cost_of_service',
    name: 'Average cost of service',
    description: 'Average price customers pay for the service.',
    unit: 'ZAR',
    valueType: 'numeric',
    category: 'ict',
    sdgs: [9],
    helpText: 'What is the average monthly or per-unit cost of your service to customers?',
    calculation: 'Total revenue / Total customers served.',
  },

  // HOUSING SPECIFIC
  {
    id: 'affordable_houses',
    name: 'Total number of affordable houses provided',
    description: 'Number of affordable housing units delivered.',
    unit: 'Number',
    valueType: 'numeric',
    category: 'housing',
    sdgs: [11],
    helpText: 'How many affordable or social housing units did your project deliver?',
    calculation: 'Count housing units completed and handed over during the reporting period.',
  },
  {
    id: 'social_housing_rental_avg',
    name: 'Average rental price per unit (social housing)',
    description: 'Average monthly rent for social housing units.',
    unit: 'ZAR',
    valueType: 'numeric',
    category: 'housing',
    sdgs: [11],
    helpText: 'What is the average monthly rent charged for your social housing units?',
    calculation: 'Total monthly rental income / Number of occupied units.',
  },
  {
    id: 'social_housing_units',
    name: 'Total number of social housing units provided',
    description: 'Total social housing units available.',
    unit: 'Number',
    valueType: 'numeric',
    category: 'housing',
    sdgs: [11],
    helpText: 'Total number of social or government-subsidised housing units in your portfolio.',
    calculation: 'Count all social housing units in your portfolio.',
  },

  // WATER SPECIFIC
  {
    id: 'water_loss_reduction_pct',
    name: 'Water Loss Reduction (%)',
    description: 'Percentage decrease in water losses.',
    unit: '%',
    valueType: 'percentage',
    category: 'water',
    sdgs: [3, 6, 14],
    helpText: 'By what percentage did you reduce water loss compared to the previous year?',
    calculation: '((Previous water loss - Current water loss) / Previous water loss) × 100',
  },
  {
    id: 'water_supplied_treated',
    name: 'Water Supplied / Treated (kL)',
    description: 'Total volume of water supplied or treated.',
    unit: 'kL',
    valueType: 'numeric',
    category: 'water',
    sdgs: [3, 6],
    helpText: 'Total kilolitres of water your system supplied or treated during the year.',
    calculation: 'Sum of all water supplied or treated in kilolitres.',
  },
  {
    id: 'water_connections',
    name: 'Number of households/businesses connected to water supply',
    description: 'Connections to water supply infrastructure.',
    unit: 'Number',
    valueType: 'numeric',
    category: 'water',
    sdgs: [6],
    helpText: 'How many homes or businesses now have a water connection through your project?',
    calculation: 'Count all active water connections.',
  },

  // LOGISTICS SPECIFIC
  {
    id: 'port_pairs_routes',
    name: 'Number of port pairs or routes served',
    description: 'Direct transport links between ports or cities.',
    unit: 'Number',
    valueType: 'numeric',
    category: 'logistics',
    sdgs: [9],
    helpText: 'How many direct routes between origin and destination points does your operation serve?',
    calculation: 'Count unique origin-destination pairs served.',
  },
  {
    id: 'road_rail_share_pct',
    name: 'Road/rail share of inland bulk/freight transport',
    description: 'Percentage of freight moved by road and rail.',
    unit: '%',
    valueType: 'percentage',
    category: 'logistics',
    sdgs: [9],
    helpText: 'What percentage of your freight is moved by road and rail combined (vs air or sea)?',
    calculation: '(Road + Rail freight tonnage / Total freight tonnage) × 100',
  },
  {
    id: 'tonnage_passengers_transported',
    name: 'Increased tonnage / Passengers transported',
    description: 'Increase in goods or people transported.',
    unit: 'Tonnes/Passengers',
    valueType: 'numeric',
    category: 'logistics',
    sdgs: [9],
    helpText: 'How much did your total freight tonnage or passenger numbers increase this year?',
    calculation: 'Current period tonnage or passengers minus prior period.',
  },
];

export const getKPI = (id: string): KPIDefinition | undefined =>
  KPI_LIST.find(k => k.id === id);

export const getKPIsBySDG = (sdgId: number): KPIDefinition[] =>
  KPI_LIST.filter(k => k.sdgs.includes(sdgId));

export const getKPIsByCategory = (category: KPICategory): KPIDefinition[] =>
  KPI_LIST.filter(k => k.category === category);
